name: robwilliams
favicon: null
layout_spectrum: 0.4256
typography_spectrum: 0.3305509
title: Musings on the future
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ffd91f'
    - '#656565'
    - '#0d0d0d'
    - '#d09e2d'
  brandStrength: 0.252195
  lightness: 0.0006913482
  saturation: 0.04540939
  rhythmicContrast: 0.01168504
purpose: []
