layout_spectrum: 0.1057546
typography_spectrum: 0.3305509
color:
  saturation: 0.04540939
  lightness: 0.0006913482
  brandStrength: 0.252195
  rhythmicContrast: 0.01168504
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: robwilliams
